config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Admin pies of site
    # Define all routes for admin here
    namespace :admin do
      resources :articles
      resources :categories
      resources :users, except: %i[new create]
      resources :teams
      resources :surveys
    end
    # Sig up and sign in in site routes
    namespace :authentication do
      resource :registration, only: %i[create new], as: "register"
      resources :confirmations, only: %i[create edit new], param: :confirmation_token
      resources :sessions, only: %i[create new], as: "login"
      get "logout", to: "sessions#destroy", as: "logout"
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"

    # resource :user, only: %i[create new]

    # Site info routes

    resource :users, except: %i[new create]
    resources :articles
    resource :user_team, only: %i[edit update show]
    delete "/user_teams/:id/delete", to: "user_teams#destroy", as: "user_team_delete"
    post "/answer", to: "surveys#create", as: "answer"
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  # Validation
  validates :question, presence: true
  validates :active_from, presence: true

  before_destroy :option_delete_all

  # Attributes
  attribute :question, :string
  attribute :active_from, :datetime
  attribute :active_to, :datetime

  has_many :options, primary_key: "id", foreign_key: "surveys_id", class_name: "SurveyOption", dependent: :destroy

  enum status: {
    unpublished: 0,
    published: 1,
    closed: 2
  }

  scope :published, -> { where("status = 1") }

  private

  # Before delete clean all connected options
  def option_delete_all
    options.each do |option|
      option.destroy
    end
  end
end

app/controllers/admin/surveys_controller.rb
module Admin
  class SurveysController < AdminController
    before_action :find_survey, only: %i[edit update destroy]
    # GET /admin/surveys
    def index
      @pagy, @surveys = pagy(Survey.all)
    end

    # GET /admin/surveys/new
    def new
      @survey = Survey.new
    end

    # POST /admin/surveys/create
    def create
      Surveys::Create.new(surveys_params).call
      redirect_to admin_surveys_url
    end

    # GET /admin/surveys/:id/edit
    def edit
      @survey = Survey.find(params[:id])
    end

    # PATCH  /admin/surveys/:id
    def update
    end

    def destroy
      Surveys::Delete.new(@survey).call
    end

    private

    def surveys_params
      surveys = params.require(:survey)
      {
        options: surveys[:options]
      }.merge!(surveys.permit(:question, :active_from, :active_to))
    end

    def find_survey
      @survey = params.has_key?(:id) ? Survey.find(params[:id]) : Survey.new
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # Create answer
  # POST /answer
  def create
    Surveys::Answers::Create.new(option, current_user)

    redirect_to root_path, notice: "You voted successfully"
  end

  private

  def answer_params
    params.require(:survey_answer).permit(:answer)
  end

  def option
    SurveyOption.find(answer_params[:answer])
  end
end

app/helpers/admin/surveys_helper.rb
module Admin::SurveysHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/admin/surveys/_form.html.erb
<div class="form-group">
    <%= form.label :question, 'Question', class: "form-label" %>
    <%= form.text_field :question, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :active_from, 'Active_from', class: "form-label" %>
    <%= form.date_field :active_from, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :active_to, 'Active to', class: "form-label" %>
    <%= form.date_field :active_to, class: 'form-control form-control-lg', required: true %>
</div>

<div class="survey-options">
    <span id="add-new-option-field" style="cursor: pointer"><h1>+</h1></span>
</div>
<div class="form-group">
    <%= form.submit 'Create', class: 'btn btn-success' %>
</div>

app/views/admin/surveys/edit.html.erb
<div class="container">
    <%= form_with(model: @survey, url: admin_surveys_url, method: :post) do |form| %>

        <%= render 'admin/surveys/form', form: form %>
    <% end %>
</div>

app/views/admin/surveys/index.html.erb
<div class="container">
    <%= link_to 'Add', new_admin_survey_path, class: 'btn btn-outline-danger' %>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Question</th>
            <th>Status</th>
            <th>Response</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <% for survey in @surveys do %>
            <tr>
                <td><%= survey.id %></td>
                <td><%= survey.question %></td>
                <td><%= survey.status %></td>
                <td><%= survey.options.first.survey_answers.length %></td>
                <td>
                    <div class="d-flex flex-column">
                        <%= link_to 'Edit', edit_admin_survey_path(survey.id), class: 'btn btn-success' %>
                        <%= button_to 'Trash', admin_survey_path(survey.id), method: :delete, class: 'btn btn-danger btn-sm' %>
                    </div>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>

    <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/surveys/new.html.erb
<div class="container">
    <%= form_with(model: @survey, url: admin_surveys_url, method: :post) do |form| %>

        <%= render 'admin/surveys/form', form: form %>
    <% end %>
</div>