config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Admin pies of site
    # Define all routes for admin here
    namespace :admin do
      resources :articles
      resources :categories
      resources :users, except: %i[new create]
      resources :teams
      resources :surveys
    end
    # Sig up and sign in in site routes
    namespace :authentication do
      resource :registration, only: %i[create new], as: "register"
      resources :confirmations, only: %i[create edit new], param: :confirmation_token
      resources :sessions, only: %i[create new], as: "login"
      get "logout", to: "sessions#destroy", as: "logout"
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"

    # resource :user, only: %i[create new]

    # Site info routes

    resource :users, except: %i[new create]
    resources :articles
    resource :user_team, only: %i[edit update show]
    delete "/user_teams/:id/delete", to: "user_teams#destroy", as: "user_team_delete"
    post "/answer", to: "surveys#create", as: "answer"
  end
end

app/models/article.rb
class Article < ApplicationRecord
  # TODO(subscribes): If user subscribes to team current articles and current article changing status(state) to published, create mail to user
  # TODO(status): after transaction send mail to successfully moderation  article
  # TODO(engines): engines must return for read subscribe chanel rss, user mapping for overwrite attr, and render xml
  #

  include AASM

  attribute :title, :string
  attribute :caption, :string
  attribute :content, :string
  attribute :is_public, :boolean, default: true
  attribute :show_comment, :boolean, default: true

  # Relationship
  belongs_to :category, foreign_key: "categories_id", primary_key: "id", optional: true # Why?
  belongs_to :user, foreign_key: "users_id", primary_key: "id", optional: true
  belongs_to :country, foreign_key: "countries_id", primary_key: "id", optional: true
  belongs_to :team, foreign_key: "teams_id", primary_key: "id", optional: true
  # belongs_to :country, foreign_key: "country"
  has_one_attached :image, dependent: :destroy

  # Validate
  validates :title, presence: true, uniqueness: { scope: :title, massage: "For each article have to unique title" }
  validates :content, presence: true
  validates :users_id, presence: true
  validates :categories_id, presence: true

  scope :all_public, -> { where("is_public = 1 OR aasm_state = 'published'") }

  # state_machine :is_public, initial: :published do
  #  event :published do
  #    # Todo send email
  #  end
  # end

  aasm do
    state :published, initial: true
    state :closed
    state :unpublished
    state :moderating

    event :publishing do
      transitions from: [:unpublished, :moderating, :closed], to: :published, after: :send_mails
    end

    event :close do
      transitions from: :published, to: :closed
    end
  end

  # Send mails about published new articles
  def send_mails
    Articles::ArticleMailerJob.perform_async(self.class, User.admins.sample, User.find(users_id))
    Articles::NoticeAboutNewArticle.perform_in(5.minute.from_now, self.class, team.users.pluck(&:email))
  end

  # Singleton
  class << self
    def most_popular
      # todo: Search most popular articles
    end

    def most_commented
      # todo: Search most commented articles
    end

    def best_of_day
      # todo: Search article from current day and get best photo
    end
  end

  def long_created_at
    # l created_at, format: :long
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::AdminController
    before_action :find_article, only: %i[show edit update delete]
    # include ServiceHandle

    # GET /admin/article
    def index
      @pagy, @articles = pagy(ArticlePolicy::Scope.new(current_user, Article).resolve)
    end

    # GET /admin/article/:id
    def show
      # parse_current_controller

      # render plain: "#{get_redirect_url!(get_redirect_action(:update))} #{get_routes} #{@route_fn} #{@controller} #{params[:controller]} <br> #{params[:action]}"
    end

    # GET /admin/article/new
    def new
      @article = Article.new
      @categories = Category.all
    end

    # POST /admin/article
    def create
      # raise params.to_s
      @article = Articles::Create.new(article_params, session[:user], params[:article][:image]).call
      # redirect_to admin_article_url
    end

    # GET /admin/article/edit
    def edit
    end

    # POST /admin/article
    def update
      authorize @article, :editable?, policy_class: ArticlePolicy

      @article = Articles::Update.new(article_params, params[:id]).call
      redirect_to admin_article_url
    end

    # POST /admin/article
    def destroy
      Articles::Delete.new(params[:id]).call
      redirect_to admin_article_url
    end

    private

    def article_params
      params.require(:article).permit(
        :image,
        :categories_id,
        :teams_id,
        :countries_id,
        :title,
        :caption,
        :content,
        :is_public,
        :show_comment
      )
    end

    # Find article by outer id
    # @return[Article]
    def find_article
      @article = Article.find(params[:id])
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<div class="form-group">
    <%= form.label :image, 'Main photo', class: "form-label" %>
    <%= form.file_field :image, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :categories_id, 'Subcategory', class: "form-label" %>
    <%= form.collection_select :categories_id, categories, :id, :title, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :categories_id, 'Teams', class: "form-label" %>
    <%= form.collection_select :teams_id, Team.all, :id, :title, class: 'form-control form-control-lg' %>
</div>
<div class="form-group">
    <%= form.label :countries_id, 'Location', class: "form-label" %>
    <%= form.collection_select :countries_id, Country.all, :id, :title, class: 'form-control form-control-lg' %>
</div>
<div class="form-group">
    <%= form.label :title, 'Article headline', class: "form-label" %>
    <%= form.text_field :title, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :caption, 'Caption', class: "form-label" %>
    <%= form.text_field :caption, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :content, 'Content', class: "form-label" %>
    <%= form.text_area :content, class: 'form-control form-control-lg', required: true %>
</div>


<div class="form-group">
    <%= form.label :is_public, 'Is public', class: "form-label" %>
    <%= form.check_box :is_public, value: '1', class: '', required: true %>
</div>
<div class="form-group">
    <%= form.label :show_comment, 'Show comment', class: "form-label" %>
    <%= form.check_box :show_comment, value: '1', class: '', required: true %>
</div>


<div class="form-group">
    <%= form.submit 'Create', class: 'btn btn-success' %>
</div>

app/views/admin/articles/destroy.html.erb
<h1>Admin::Articles#destroy</h1>
<p>Find me in app/views/admin/articles/destroy.html.erb</p>

app/views/admin/articles/edit.html.erb
<div class="container">
    <%= form_with(model: @article, url: admin_article_url, method: :patch) do |form| %>

        <% if @article.errors.any? %>
            <div style="color: red">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                <ul>
                    <% @article.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <% if @article.image.attached? %>
            <%= image_tag @article.image, style: 'width: 250px', loading: 'lazy', decoding: 'async' %>

        <% end %>
        <%= render 'admin/articles/form', form: form, categories: Category.all %>
    <% end %>
</div>

app/views/admin/articles/index.html.erb
<div class="container">
    <%= link_to 'Add', new_admin_article_path, class: 'btn btn-outline-danger' %>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Title</th>
            <th>Category</th>
            <th>Public?</th>
            <th>Author</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <% for article in @articles do %>
            <tr>
                <td><%= article.id %></td>

                <td>
                    <% if article.image.attached? %>
                        <%= image_tag article.image, style: 'width: 250px', loading: 'lazy', decoding: 'async' %>
                    <% else %>
                        No image
                    <% end %>
                </td>

                <td><%= article.title %></td>
                <td><%= article.category.title %></td>
                <td><%= article.is_public %></td>
                <td><%= article.user.first_name unless article.user.nil? %></td>
                <td><%= article.long_created_at %></td>
                <td><%= article.updated_at %></td>
                <td>
                    <div class="d-flex flex-column">
                        <%= link_to 'Edit', edit_admin_article_path(article.id), class: 'btn btn-success' %>
                        <%= button_to 'Trash', admin_article_path(article.id), method: :delete, class: 'btn btn-danger btn-sm' %>
                    </div>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>

    <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/articles/new.html.erb
<div class="container" >
    <%= form_with(model: @article, url: admin_articles_url, method: :post) do |form| %>

        <%= render 'admin/articles/form', form: form, categories: Category.all %>
    <% end %>
</div>

app/views/admin/articles/show.html.erb
<h1>Admin::Articles#show</h1>
<p>Find me in app/views/admin/articles/show.html.erb</p>

app/views/admin/articles/update.html.erb
<h1>Admin::Articles#update</h1>
<p>Find me in app/views/admin/articles/update.html.erb</p>