config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Admin pies of site
    # Define all routes for admin here
    namespace :admin do
      resources :articles
      resources :categories
      resources :users, except: %i[new create]
      resources :teams
      resources :surveys
    end
    # Sig up and sign in in site routes
    namespace :authentication do
      resource :registration, only: %i[create new], as: "register"
      resources :confirmations, only: %i[create edit new], param: :confirmation_token
      resources :sessions, only: %i[create new], as: "login"
      get "logout", to: "sessions#destroy", as: "logout"
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"

    # resource :user, only: %i[create new]

    # Site info routes

    resource :users, except: %i[new create]
    resources :articles
    resource :user_team, only: %i[edit update show]
    delete "/user_teams/:id/delete", to: "user_teams#destroy", as: "user_team_delete"
    post "/answer", to: "surveys#create", as: "answer"
  end
end

app/models/category.rb
class Category < ApplicationRecord
  before_destroy :delete_articles

  # Validates
  validates :title, uniqueness: {scope: :title, massage: "Category title hos to get unique key"}

  # Relations
  has_many :articles, primary_key: "categories_id", foreign_key: "id", dependent: :destroy
  has_many :children, class_name: "Category", foreign_key: "parent_id", dependent: :destroy
  has_many :teams, primary_key: "categories_id", foreign_key: "id", dependent: :destroy

  belongs_to :parent, class_name: "Category", optional: true

  # Get all sub categories for current category
  #   all_sub_categories # get array of hash
  #   # @example:
  #   # [
  #   #   {
  #   #      :id => 5,
  #   #      :title => 'Title'
  #   #      :children => [
  #   #        :id => 3,
  #   #        :title => 'TEst'
  #   #        ...etc
  #   #      ]
  #   #    }
  #   #  ]
  # @return[Array]
  def all_sub_categories
    return [] if children.empty?

    children.map do |category|
      {
        id: category.id,
        title: category.title,
        children: category.all_sub_categories
      }
    end
  end

  private

  # Before delete category we need delete all connected articles
  # And remove all sub categories
  def delete_articles
    @articles.each do |article|
      article.delete
    end
    @children.each do |category|
      category.remove
    end
  end

  class << self
    # Select all main categories
    def all_main
      Category.where("parent_id IS NULL")
    end
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::AdminController
    # GET /admin/categories
    def index
      @pagy, @categories = pagy(Category.all)
    end

    # Get /admin/categories/new
    def new
      # User for create select parent category
      @category = Category.new
    end

    # GET /admin/categories/create
    def create
      Categories::Create.new(category_params).call
      redirect_to admin_categories_url
    end

    def update
      Categories::Update.new(params[:id], category_params).call
      redirect_to admin_categories_url
    end

    def edit
      @category = Category.find(params[:id])
    end

    def destroy
      Categories::Delete.new(params[:id]).call
    end

    def show
    end

    private

    def category_params
      params.require(:category).permit(:title, :parent_id)
    end

  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form-fields.html.erb
<div class="form-group">
    <%= form.label :title, 'Title', class: "form-label" %>
    <%= form.text_field :title, class: 'form-control form-control-lg', required: true %>
</div>
<div class="form-group">
    <%= form.label :parent_id, 'Parent', class: "form-label" %>
    <%= form.collection_select :parent_id, ([] << categories).flatten!, :id, :title, class: 'form-control form-control-lg' %>
</div>
<div class="form-group">
    <%= form.submit 'Create', class: 'btn btn-success' %>
</div>

app/views/admin/categories/edit.html.erb
<div class="container">
    <%= form_with(model: @category, url: admin_category_url, method: :patch ) do |form| %>
        <%= render 'admin/categories/form-fields', form: form, categories: Category.all %>
    <% end %>

</div>

app/views/admin/categories/index.html.erb
<div class="container">
    <%= link_to 'Add', new_admin_category_path, class: 'btn btn-outline-danger' %>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Parent</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <% for category in @categories do %>
            <tr>
                <td><%= category.id %></td>
                <td><%= category.title %></td>
                <td>
                    <% if category.parent_id %>
                        <%= category.parent.title %>
                    <% end %>
                </td>
                <td><%= category.created_at %></td>
                <td><%= category.updated_at %></td>
                <td>
                    <div class="d-flex flex-column">
                        <%= link_to 'Edit', edit_admin_category_path(category.id), class: 'btn btn-success' %>
                        <%= button_to 'Trash', admin_category_path(category.id), method: :delete, class: 'btn btn-danger btn-sm' %>
                    </div>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
    <% form_with(model: @categories, url: admin_categories_url, method: :post) do |form| %>
        <%= render 'admin/categories/form-fields', form: form, categories: Category.all %>
    <% end %>

</div>