config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Admin pies of site
    # Define all routes for admin here
    namespace :admin do
      resources :articles
      resources :categories
      resources :users, except: %i[new create]
      resources :teams
      resources :surveys
    end
    # Sig up and sign in in site routes
    namespace :authentication do
      resource :registration, only: %i[create new], as: "register"
      resources :confirmations, only: %i[create edit new], param: :confirmation_token
      resources :sessions, only: %i[create new], as: "login"
      get "logout", to: "sessions#destroy", as: "logout"
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"

    # resource :user, only: %i[create new]

    # Site info routes

    resource :users, except: %i[new create]
    resources :articles
    resource :user_team, only: %i[edit update show]
    delete "/user_teams/:id/delete", to: "user_teams#destroy", as: "user_team_delete"
    post "/answer", to: "surveys#create", as: "answer"
  end
end

app/views/include/admin/_sidebar.html.erb
<div class="center-block col-md-3">
    <div class="container d-flex flex-column p-5">
        <nav id="main-nav" class="">
            <ul>
                <li><%= link_to 'Todo category', root_path, class: 'menu-item__text'  %></li>
                <li class="p-2"><%= link_to 'Articles', admin_articles_url, class: 'menu-item__text' %></li>
                <li class="p-2"><%= link_to 'Team Hub', admin_teams_url, class: 'menu-item__text' %></li>
                <li class="p-2"><%= link_to 'Users', admin_users_url, class: 'menu-item__text' %></li>
            </ul>
        </nav>

    </div>
</div>